myuploadurl:
  url: F:/ideawork/IDEA/blog
server:
  port: 8081
  tomcat:
    accesslog:
      buffered: true
      directory: /home/log/tomcat
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: '%t | %{X-Real-IP}i | %b | %B | %H | %l | %m | %p | %q | %r | %s | %S | %u | %U | %v | %D | %T | %{Cookie}i | %{User-Agent}i | %{a}r'
      prefix: access_log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
      suffix: .log
spring:
  application:
    name: support
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: Mysql!@#456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1

mybatis-plus:
  mapper-locations: classpath*:com/person/blog/blog/mapper/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.person.blog.blog.mapper: debug